version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./casino_app:/app
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
